# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['python/Localizable Tool.py']
# 自写模块放在DATA_FILES列表中
DATA_FILES = ['python/StringsFileUtil.py', 'python/Xls2Xml.py', 'python/Xml2Xls.py', 'python/Log.py',
              'python/Strings2Xls.py', 'python/XlsFileUtil.py', 'python/XmlFileUtil.py', 'python/Strings2Xml.py',
              'python/Xls2Strings.py']
# 第三方库放在OPTIONS下的includes对应的列表中
OPTIONS = {'includes': []}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['clipboard', 'PyQt5']
)
