# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Localizable Tool.py']
# 自写模块放在DATA_FILES列表中
DATA_FILES = ['StringsFileUtil.py', 'Xls2Xml.py', 'Xml2Xls.py', 'Log.py', 'Strings2Xls.py', 'XlsFileUtil.py',
              'XmlFileUtil.py', 'Strings2Xml.py', 'Xls2Strings.py']
# 第三方库放在OPTIONS下的includes对应的列表中
OPTIONS = {'includes': []}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['clipboard', 'PyQt5']
)
